## Autogenerated config.py
## Documentation:
##   qute://help/configuring.html
##   qute://help/settings.html

## This is here so configs done via the GUI are still loaded.
## Remove it to not load settings done via the GUI.
import os

config.load_autoconfig()

## Aliases for commands. The keys of the given dictionary are the
## aliases, while the values are the commands they map to.
## Type: Dict
c.aliases = { 'w': 'session-save', 'q': 'quit', 'wq': 'quit --save'}

pdf_dir = '~/.qutebrowser/pdf/{}'
c.aliases.update({
    'config-load': 'config-source',
    'pdf': 'print -f '+pdf_dir,
    'echo': 'message-info',
    'e': 'session-load'
    })

config.bind('V',  'hint links spawn mpv {hint-url}')
config.bind(';V', 'spawn mpv {url}')

config.bind('yy', 'yank -s')
config.bind('Y', 'yank')

config.bind('E', 'edit-url')

config.bind(',e', 'config-edit')
config.bind(',s', 'config-source ;; message-info "Sourced config file"')

config.bind(',v', 'view-source')

config.bind('tc', 'tab-clone')
config.bind('tg', 'tab-clone')
config.bind('tm', 'tab-move')
config.bind('<ctrl+h>', 'tab-move -')
config.bind('<ctrl+l>', 'tab-move +')

config.bind('<ctrl+c>', 'stop')

config.bind('dc', 'download-cancel')

config.bind('<ctrl+shift+B>', 'rl-backward-word', mode='command')
config.bind('<ctrl+shift+B>', 'rl-backward-word', mode='prompt')
config.bind('<ctrl+shift+F>', 'rl-forward-word', mode='command')
config.bind('<ctrl+shift+F>', 'rl-forward-word', mode='prompt')
config.bind('<ctrl+w>', 'rl-backward-kill-word', mode='prompt')

config.bind('T', 'tab-focus last')

config.bind('<alt+/>', 'cmd-set-text -s :tab-select ')
config.bind('D', 'config-cycle colors.webpage.darkmode.enabled false true')

# Settings
c.auto_save.session = True
c.session.default_name = "default"

#TODO dynamic download dirs
# config.bind('D', )

## used by prepending the search engine name to the search term, e.g.
## `:open gh qutebrowser`.
## Type: Dict
c.url.searchengines = {
    # Generic
    'DEFAULT': 'https://google.com/search?q={}',
    'duck': 'https://duckduckgo.com/?q={}',
    'gh': 'https://github.com/search/?q={}',
    'go': 'https://google.com/search?q={}',
    'aw': 'https://wiki.archlinux.org/index.php?search={}',
    'di': 'https://dictionary.com/browse/{}',
    'dict': 'https://dictionary.com/browse/{}',
    'th': 'https://thesaurus.com/browse/{}?s=t',
    'the': 'https://thesaurus.com/browse/{}?s=t',
    'yt': 'https://youtube.com/results?search_query={}',
    'az': 'https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords={}',
    'arch': 'https://gitlab.archlinux.org/archlinux/packaging/packages?filter={}',

    ### Everything from here down should have a corresponding entry in quickmarks ###

    # AWS
    'aws/EC2': 'https://console.aws.amazon.com/ec2/home?#Instances:instanceState=running;search=:{};v=3;$case=tags:true%5C,client:false;$regex=tags:false%5C,client:false',
    'aws/LB': 'https://console.aws.amazon.com/ec2/home?#LoadBalancers:search=:{};v=3;$case=tags:false%5C,client:false;$regex=tags:false%5C,client:false',
    'aws/Lambda': 'https://console.aws.amazon.com/lambda/home?#/functions?fo=and&o0=%3A&v0={}',
    'aws/Secret': 'https://console.aws.amazon.com/secretsmanager/listsecrets?search=all%3D{}',

    # Documentation
    'docs/aws': 'https://docs.aws.amazon.com/search/doc-search.html?searchPath=documentation-product&searchQuery={}',
    'docs/awscli': 'https://docs.aws.amazon.com/cli/latest/reference/{}',
    'docs/terraform/aws': 'https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/{}',
}

# Neovide as default editor
c.editor.command = [
    "neovide",
    "--wsl",
    "{file}",
    "--" "-c",
    "normal {line}G{column0}l"
]

# Windows doesn't have primary selection, so simplify the binding
if os.name == 'nt':
    config.bind('P', 'open -t -- {clipboard}')
    config.bind('p', 'open -- {clipboard}')
