source ~/.config/tmux/options
source ~/.config/tmux/bindings
source ~/.config/tmux/status
source ~/.config/tmux/Music

# execute on startup only
if-shell -F "$TMUX_STARTED" "source ~/.config/tmux/after" "source ~/.config/tmux/startup"
TMUX_STARTED=1
source ~/.private/tmux
